CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Cantieri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(200) NOT NULL,
    "Indirizzo" character varying(255),
    "ResponsabileCantiere" character varying(200),
    "DirezioneLavori" character varying(200),
    "Committente" character varying(200),
    "Appaltatore" character varying(200),
    "DataInizioLavori" date,
    "DataPrevistaFineLavori" date,
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Cantieri__3214EC078EDC8A94" PRIMARY KEY ("Id")
);

CREATE TABLE "CategorieDpi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Categori__3214EC0788DB269E" PRIMARY KEY ("Id")
);

CREATE TABLE "CategorieMateriale" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Categori__3214EC0722FDA59A" PRIMARY KEY ("Id")
);

CREATE TABLE "EsitiVisitaMedica" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__EsitiVis__3214EC0777431164" PRIMARY KEY ("Id")
);

CREATE TABLE "Fornitori" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RagioneSociale" character varying(200) NOT NULL,
    "PartitaIva" character varying(11),
    "CodiceFiscale" character varying(16),
    "Telefono" character varying(50),
    "Email" character varying(255),
    "Indirizzo" character varying(255),
    "Citta" character varying(100),
    "Provincia" character varying(2),
    "Cap" character varying(5),
    "Note" character varying(1000),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Fornitor__3214EC0793EC0173" PRIMARY KEY ("Id")
);

CREATE TABLE "Mansioni" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Mansioni__3214EC0711E4A07C" PRIMARY KEY ("Id")
);

CREATE TABLE "Permessi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codice" character varying(150) NOT NULL,
    "Risorsa" character varying(100) NOT NULL,
    "Azione" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Permessi__3214EC07A0B017E1" PRIMARY KEY ("Id")
);

CREATE TABLE "Ruoli" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Ruoli__3214EC0763C9D54C" PRIMARY KEY ("Id")
);

CREATE TABLE "StatiAssegnazione" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__StatiAss__3214EC07CE1ACDDF" PRIMARY KEY ("Id")
);

CREATE TABLE "TipiAssenza" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_TipiAssenza" PRIMARY KEY ("Id")
);

CREATE TABLE "TipiDocumento" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__TipiDocu__3214EC07CA798AC6" PRIMARY KEY ("Id")
);

CREATE TABLE "TipiMovimentoMateriale" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Segno" smallint NOT NULL,
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__TipiMovi__3214EC07863B191C" PRIMARY KEY ("Id")
);

CREATE TABLE "TipiVisitaMedica" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__TipiVisi__3214EC07FEB77A1C" PRIMARY KEY ("Id")
);

CREATE TABLE "TipologieMezzo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descrizione" character varying(255),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Tipologi__3214EC0789568B9B" PRIMARY KEY ("Id")
);

CREATE TABLE "DocumentiCantieri" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CantiereId" integer NOT NULL,
    "NomeFile" character varying(255) NOT NULL,
    "PercorsoFile" character varying(500) NOT NULL,
    "Estensione" character varying(20),
    "ContentType" character varying(100),
    "DataDocumento" date,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Document__3214EC07CANTIERE" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentiCantieri_Cantieri" FOREIGN KEY ("CantiereId") REFERENCES "Cantieri" ("Id")
);

CREATE TABLE "Dpi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codice" character varying(50),
    "Nome" character varying(150) NOT NULL,
    "CategoriaDpiId" integer,
    "Descrizione" character varying(500),
    "Taglia" character varying(50),
    "Marca" character varying(100),
    "Modello" character varying(100),
    "Barcode" character varying(100),
    "FornitoreId" integer,
    "DurataGiorni" integer,
    "QuantitaDisponibile" numeric(18,2) NOT NULL DEFAULT 0.0,
    "QuantitaMinima" numeric(18,2) NOT NULL DEFAULT 0.0,
    "RichiedeTaglia" boolean NOT NULL DEFAULT FALSE,
    "HaScadenza" boolean NOT NULL,
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Dpi__3214EC0738F9D218" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Dpi_CategorieDpi" FOREIGN KEY ("CategoriaDpiId") REFERENCES "CategorieDpi" ("Id"),
    CONSTRAINT "FK_Dpi_Fornitori" FOREIGN KEY ("FornitoreId") REFERENCES "Fornitori" ("Id")
);

CREATE TABLE "Materiali" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codice" character varying(50),
    "Nome" character varying(150) NOT NULL,
    "CategoriaMaterialeId" integer,
    "Descrizione" character varying(500),
    "UnitaMisura" character varying(30),
    "QuantitaAttuale" numeric(18,2) NOT NULL,
    "ScortaMinima" numeric(18,2),
    "Barcode" character varying(100),
    "FornitoreId" integer,
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Material__3214EC07764A8871" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Materiali_CategorieMateriale" FOREIGN KEY ("CategoriaMaterialeId") REFERENCES "CategorieMateriale" ("Id"),
    CONSTRAINT "FK_Materiali_Fornitori" FOREIGN KEY ("FornitoreId") REFERENCES "Fornitori" ("Id")
);

CREATE TABLE "Dipendenti" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Matricola" character varying(50),
    "Nome" character varying(100) NOT NULL,
    "Cognome" character varying(100) NOT NULL,
    "CodiceFiscale" character varying(16),
    "DataNascita" date,
    "LuogoNascita" character varying(150),
    "Telefono" character varying(50),
    "Email" character varying(255),
    "Indirizzo" character varying(255),
    "Citta" character varying(100),
    "Provincia" character varying(2),
    "Cap" character varying(5),
    "DataAssunzione" date,
    "DataCessazione" date,
    "HaPatente" boolean NOT NULL DEFAULT FALSE,
    "CategoriaPatente" character varying(20),
    "MansioneId" integer,
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Dipenden__3214EC079E4CF650" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Dipendenti_Mansioni" FOREIGN KEY ("MansioneId") REFERENCES "Mansioni" ("Id")
);

CREATE TABLE "RuoliPermessi" (
    "RuoloId" integer NOT NULL,
    "PermessoId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_RuoliPermessi" PRIMARY KEY ("RuoloId", "PermessoId"),
    CONSTRAINT "FK_RuoliPermessi_Permessi" FOREIGN KEY ("PermessoId") REFERENCES "Permessi" ("Id"),
    CONSTRAINT "FK_RuoliPermessi_Ruoli" FOREIGN KEY ("RuoloId") REFERENCES "Ruoli" ("Id")
);

CREATE TABLE "Mezzi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Targa" character varying(20),
    "NumeroTelaio" character varying(100),
    "CodiceInterno" character varying(50),
    "TipologiaMezzoId" integer,
    "Marca" character varying(100),
    "Modello" character varying(100),
    "AnnoImmatricolazione" integer,
    "DataImmatricolazione" date,
    "DataRevisione" date,
    "DataScadenzaBollo" date,
    "DataScadenzaAssicurazione" date,
    "DataTagliando" date,
    "FornitoreId" integer,
    "TipoPossesso" character varying(20),
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Mezzi__3214EC07B3567637" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Mezzi_Fornitori" FOREIGN KEY ("FornitoreId") REFERENCES "Fornitori" ("Id"),
    CONSTRAINT "FK_Mezzi_TipologieMezzo" FOREIGN KEY ("TipologiaMezzoId") REFERENCES "TipologieMezzo" ("Id")
);

CREATE TABLE "AssegnazioniDpi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "DpiId" integer NOT NULL,
    "CantiereId" integer,
    "Quantita" integer NOT NULL DEFAULT 1,
    "StatoAssegnazioneId" integer NOT NULL,
    "DataConsegna" date NOT NULL,
    "DataScadenza" date,
    "DataRestituzione" date,
    "FirmaConsegna" boolean NOT NULL,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Assegnaz__3214EC07C61ED0C1" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssegnazioniDpi_Cantieri" FOREIGN KEY ("CantiereId") REFERENCES "Cantieri" ("Id"),
    CONSTRAINT "FK_AssegnazioniDpi_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_AssegnazioniDpi_Dpi" FOREIGN KEY ("DpiId") REFERENCES "Dpi" ("Id"),
    CONSTRAINT "FK_AssegnazioniDpi_StatiAssegnazione" FOREIGN KEY ("StatoAssegnazioneId") REFERENCES "StatiAssegnazione" ("Id")
);

CREATE TABLE "AssegnazioniMateriali" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaterialeId" integer NOT NULL,
    "DipendenteId" integer,
    "CantiereId" integer,
    "Quantita" numeric(18,2) NOT NULL,
    "StatoAssegnazioneId" integer NOT NULL,
    "DataAssegnazione" timestamp with time zone NOT NULL,
    "DataRestituzione" timestamp with time zone,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Assegnaz__3214EC0713A04FEE" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssegnazioniMateriali_Cantieri" FOREIGN KEY ("CantiereId") REFERENCES "Cantieri" ("Id"),
    CONSTRAINT "FK_AssegnazioniMateriali_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_AssegnazioniMateriali_Materiali" FOREIGN KEY ("MaterialeId") REFERENCES "Materiali" ("Id"),
    CONSTRAINT "FK_AssegnazioniMateriali_StatiAssegnazione" FOREIGN KEY ("StatoAssegnazioneId") REFERENCES "StatiAssegnazione" ("Id")
);

CREATE TABLE "Assenze" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "TipoAssenzaId" integer NOT NULL,
    "DataInizio" date NOT NULL,
    "DataFine" date NOT NULL,
    "Giorni" integer NOT NULL,
    "Note" character varying(1000),
    "DataRichiesta" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "Stato" character varying(30) NOT NULL DEFAULT 'richiesto',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Assenze" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Assenze_DataFine_DataInizio" CHECK ("DataFine" >= "DataInizio"),
    CONSTRAINT "CK_Assenze_Giorni" CHECK ("Giorni" > 0),
    CONSTRAINT "CK_Assenze_Stato" CHECK ("Stato" IN ('richiesto', 'approvato', 'rimandato', 'rifiutato')),
    CONSTRAINT "FK_Assenze_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_Assenze_TipiAssenza" FOREIGN KEY ("TipoAssenzaId") REFERENCES "TipiAssenza" ("Id")
);

CREATE TABLE "MovimentiMateriale" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MaterialeId" integer NOT NULL,
    "TipoMovimentoMaterialeId" integer NOT NULL,
    "Quantita" numeric(18,2) NOT NULL,
    "DataMovimento" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "DipendenteId" integer,
    "CantiereId" integer,
    "RiferimentoTabella" character varying(100),
    "RiferimentoId" integer,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK__Moviment__3214EC07522EA9D9" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MovimentiMateriale_Cantieri" FOREIGN KEY ("CantiereId") REFERENCES "Cantieri" ("Id"),
    CONSTRAINT "FK_MovimentiMateriale_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_MovimentiMateriale_Materiali" FOREIGN KEY ("MaterialeId") REFERENCES "Materiali" ("Id"),
    CONSTRAINT "FK_MovimentiMateriale_TipiMovimentoMateriale" FOREIGN KEY ("TipoMovimentoMaterialeId") REFERENCES "TipiMovimentoMateriale" ("Id")
);

CREATE TABLE "Utenti" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "Email" character varying(255),
    "PasswordHash" character varying(500) NOT NULL,
    "Nome" character varying(100),
    "Cognome" character varying(100),
    "DipendenteId" integer,
    "Attivo" boolean NOT NULL DEFAULT TRUE,
    "MustChangePassword" boolean NOT NULL DEFAULT TRUE,
    "UltimoAccessoAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Utenti__3214EC07AC96C369" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Utenti_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id")
);

CREATE TABLE "VisiteMediche" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "TipoVisitaMedicaId" integer NOT NULL,
    "DataVisita" date NOT NULL,
    "DataScadenza" date,
    "EsitoVisitaMedicaId" integer,
    "Idoneo" boolean,
    "Prescrizioni" character varying(2000),
    "MedicoCompetente" character varying(200),
    "StrutturaSanitaria" character varying(200),
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__VisiteMe__3214EC07C60CE5B8" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VisiteMediche_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_VisiteMediche_EsitiVisitaMedica" FOREIGN KEY ("EsitoVisitaMedicaId") REFERENCES "EsitiVisitaMedica" ("Id"),
    CONSTRAINT "FK_VisiteMediche_TipiVisitaMedica" FOREIGN KEY ("TipoVisitaMedicaId") REFERENCES "TipiVisitaMedica" ("Id")
);

CREATE TABLE "AssegnazioniMezzi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MezzoId" integer NOT NULL,
    "DipendenteId" integer,
    "CantiereId" integer,
    "StatoAssegnazioneId" integer NOT NULL,
    "DataInizio" timestamp with time zone NOT NULL,
    "DataFine" timestamp with time zone,
    "KmConsegna" integer,
    "KmRientro" integer,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Assegnaz__3214EC0706704BD8" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssegnazioniMezzi_Cantieri" FOREIGN KEY ("CantiereId") REFERENCES "Cantieri" ("Id"),
    CONSTRAINT "FK_AssegnazioniMezzi_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_AssegnazioniMezzi_Mezzi" FOREIGN KEY ("MezzoId") REFERENCES "Mezzi" ("Id"),
    CONSTRAINT "FK_AssegnazioniMezzi_StatiAssegnazione" FOREIGN KEY ("StatoAssegnazioneId") REFERENCES "StatiAssegnazione" ("Id")
);

CREATE TABLE "DocumentiMezzi" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MezzoId" integer NOT NULL,
    "TipoDocumentoId" integer,
    "NomeFile" character varying(255) NOT NULL,
    "PercorsoFile" character varying(500) NOT NULL,
    "Estensione" character varying(20),
    "ContentType" character varying(100),
    "DataDocumento" date,
    "DataScadenza" date,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK__Document__3214EC07D88B4A2B" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentiMezzi_Mezzi" FOREIGN KEY ("MezzoId") REFERENCES "Mezzi" ("Id"),
    CONSTRAINT "FK_DocumentiMezzi_TipiDocumento" FOREIGN KEY ("TipoDocumentoId") REFERENCES "TipiDocumento" ("Id")
);

CREATE TABLE "CartelleDocumentiDipendenti" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "ParentCartellaId" integer,
    "Nome" character varying(150) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    "CreatedByUtenteId" integer,
    CONSTRAINT "PK_CartelleDocumentiDipendenti" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartelleDocumentiDipendenti_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_CartelleDocumentiDipendenti_Parent" FOREIGN KEY ("ParentCartellaId") REFERENCES "CartelleDocumentiDipendenti" ("Id"),
    CONSTRAINT "FK_CartelleDocumentiDipendenti_Utenti_CreatedBy" FOREIGN KEY ("CreatedByUtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "ExpenseRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "DataSpesa" date NOT NULL,
    "CategoriaSpesa" character varying(150) NOT NULL,
    "Descrizione" character varying(1000) NOT NULL,
    "Importo" numeric(18,2) NOT NULL,
    "Valuta" character varying(3) NOT NULL,
    "MetodoPagamento" character varying(100) NOT NULL,
    "Stato" character varying(30) NOT NULL DEFAULT 'IN_ATTESA',
    "AllegatoNomeFile" character varying(255),
    "AllegatoPercorsoFile" character varying(500),
    "AllegatoContentType" character varying(100),
    "AllegatoEstensione" character varying(20),
    "NotaGestione" character varying(1000),
    "GestitoDaUtenteId" integer,
    "GestitoAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ExpenseRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_ExpenseRequests_Importo" CHECK ("Importo" > 0),
    CONSTRAINT "CK_ExpenseRequests_Stato" CHECK ("Stato" IN ('IN_ATTESA', 'APPROVATA', 'RIFIUTATA', 'IN_REVISIONE')),
    CONSTRAINT "FK_ExpenseRequests_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_ExpenseRequests_Utenti_GestitoDa" FOREIGN KEY ("GestitoDaUtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "IssueReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "Categoria" character varying(100) NOT NULL,
    "Oggetto" character varying(200) NOT NULL,
    "Luogo" character varying(200),
    "Descrizione" character varying(1000) NOT NULL,
    "Priorita" character varying(30) NOT NULL,
    "Note" character varying(1000),
    "Stato" character varying(30) NOT NULL DEFAULT 'IN_ATTESA',
    "NotaGestione" character varying(1000),
    "GestitoDaUtenteId" integer,
    "GestitoAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_IssueReports" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_IssueReports_Stato" CHECK ("Stato" IN ('IN_ATTESA', 'APPROVATA', 'RIFIUTATA', 'IN_REVISIONE')),
    CONSTRAINT "FK_IssueReports_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_IssueReports_Utenti_GestitoDa" FOREIGN KEY ("GestitoDaUtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "MaterialRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "MaterialeRichiesto" character varying(200) NOT NULL,
    "Quantita" numeric(18,2) NOT NULL,
    "Motivazione" character varying(1000) NOT NULL,
    "Priorita" character varying(30) NOT NULL,
    "DataDesiderata" date NOT NULL,
    "Note" character varying(1000),
    "Stato" character varying(30) NOT NULL DEFAULT 'IN_ATTESA',
    "NotaGestione" character varying(1000),
    "GestitoDaUtenteId" integer,
    "GestitoAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_MaterialRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_MaterialRequests_Quantita" CHECK ("Quantita" > 0),
    CONSTRAINT "CK_MaterialRequests_Stato" CHECK ("Stato" IN ('IN_ATTESA', 'APPROVATA', 'RIFIUTATA', 'IN_REVISIONE')),
    CONSTRAINT "FK_MaterialRequests_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_MaterialRequests_Utenti_GestitoDa" FOREIGN KEY ("GestitoDaUtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UtenteId" integer NOT NULL,
    "TokenHash" character varying(500) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "RevokedAt" timestamp with time zone,
    "CreatedByIp" character varying(100),
    "UserAgent" character varying(500),
    CONSTRAINT "PK__RefreshT__3214EC078E3ABF53" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Utenti" FOREIGN KEY ("UtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "UtentiRuoli" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UtenteId" integer NOT NULL,
    "RuoloId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_UtentiRuoli" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UtentiRuoli_Ruoli" FOREIGN KEY ("RuoloId") REFERENCES "Ruoli" ("Id"),
    CONSTRAINT "FK_UtentiRuoli_Utenti" FOREIGN KEY ("UtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "UtentiVisibilita" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UtenteId" integer NOT NULL,
    "Chiave" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_UtentiVisibilita" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UtentiVisibilita_Chiave" CHECK ("Chiave" IN ('dashboard', 'dipendenti', 'magazzino', 'attrezzature', 'dpi', 'mezzi', 'cantieri', 'segreteria')),
    CONSTRAINT "FK_UtentiVisibilita_Utenti" FOREIGN KEY ("UtenteId") REFERENCES "Utenti" ("Id")
);

CREATE TABLE "DocumentiDipendenti" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DipendenteId" integer NOT NULL,
    "CartellaId" integer,
    "TipoDocumentoId" integer,
    "NomeFile" character varying(255) NOT NULL,
    "NomeFileSalvato" character varying(255),
    "PercorsoFile" character varying(500) NOT NULL,
    "Estensione" character varying(20),
    "ContentType" character varying(100),
    "DimensioneBytes" bigint NOT NULL DEFAULT 0,
    "DataDocumento" date,
    "DataScadenza" date,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    "UploadedByUtenteId" integer,
    CONSTRAINT "PK__Document__3214EC07260F04D2" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentiDipendenti_Cartelle" FOREIGN KEY ("CartellaId") REFERENCES "CartelleDocumentiDipendenti" ("Id"),
    CONSTRAINT "FK_DocumentiDipendenti_Dipendenti" FOREIGN KEY ("DipendenteId") REFERENCES "Dipendenti" ("Id"),
    CONSTRAINT "FK_DocumentiDipendenti_TipiDocumento" FOREIGN KEY ("TipoDocumentoId") REFERENCES "TipiDocumento" ("Id"),
    CONSTRAINT "FK_DocumentiDipendenti_Utenti_UploadedBy" FOREIGN KEY ("UploadedByUtenteId") REFERENCES "Utenti" ("Id")
);

CREATE INDEX "IX_AssegnazioniDpi_CantiereId" ON "AssegnazioniDpi" ("CantiereId");

CREATE INDEX "IX_AssegnazioniDpi_DataScadenza" ON "AssegnazioniDpi" ("DataScadenza");

CREATE INDEX "IX_AssegnazioniDpi_DipendenteId" ON "AssegnazioniDpi" ("DipendenteId");

CREATE INDEX "IX_AssegnazioniDpi_DpiId" ON "AssegnazioniDpi" ("DpiId");

CREATE INDEX "IX_AssegnazioniDpi_StatoAssegnazioneId" ON "AssegnazioniDpi" ("StatoAssegnazioneId");

CREATE INDEX "IX_AssegnazioniMateriali_CantiereId" ON "AssegnazioniMateriali" ("CantiereId");

CREATE INDEX "IX_AssegnazioniMateriali_DataAssegnazione" ON "AssegnazioniMateriali" ("DataAssegnazione");

CREATE INDEX "IX_AssegnazioniMateriali_DipendenteId" ON "AssegnazioniMateriali" ("DipendenteId");

CREATE INDEX "IX_AssegnazioniMateriali_MaterialeId" ON "AssegnazioniMateriali" ("MaterialeId");

CREATE INDEX "IX_AssegnazioniMateriali_StatoAssegnazioneId" ON "AssegnazioniMateriali" ("StatoAssegnazioneId");

CREATE INDEX "IX_AssegnazioniMezzi_CantiereId" ON "AssegnazioniMezzi" ("CantiereId");

CREATE INDEX "IX_AssegnazioniMezzi_DataInizio" ON "AssegnazioniMezzi" ("DataInizio");

CREATE INDEX "IX_AssegnazioniMezzi_DipendenteId" ON "AssegnazioniMezzi" ("DipendenteId");

CREATE INDEX "IX_AssegnazioniMezzi_MezzoId" ON "AssegnazioniMezzi" ("MezzoId");

CREATE INDEX "IX_AssegnazioniMezzi_StatoAssegnazioneId" ON "AssegnazioniMezzi" ("StatoAssegnazioneId");

CREATE INDEX "IX_Assenze_DataRichiesta" ON "Assenze" ("DataRichiesta");

CREATE INDEX "IX_Assenze_DipendenteId" ON "Assenze" ("DipendenteId");

CREATE INDEX "IX_Assenze_Stato" ON "Assenze" ("Stato");

CREATE INDEX "IX_Assenze_TipoAssenzaId" ON "Assenze" ("TipoAssenzaId");

CREATE INDEX "IX_Cantieri_Nome" ON "Cantieri" ("Nome");

CREATE INDEX "IX_CartelleDocumentiDipendenti_CreatedByUtenteId" ON "CartelleDocumentiDipendenti" ("CreatedByUtenteId");

CREATE INDEX "IX_CartelleDocumentiDipendenti_DipendenteId" ON "CartelleDocumentiDipendenti" ("DipendenteId");

CREATE INDEX "IX_CartelleDocumentiDipendenti_ParentCartellaId" ON "CartelleDocumentiDipendenti" ("ParentCartellaId");

CREATE UNIQUE INDEX "UX_CartelleDocumentiDipendenti_Dipendente_Nome_Root" ON "CartelleDocumentiDipendenti" ("DipendenteId", "Nome") WHERE "ParentCartellaId" IS NULL;

CREATE UNIQUE INDEX "UX_CartelleDocumentiDipendenti_Dipendente_Parent_Nome" ON "CartelleDocumentiDipendenti" ("DipendenteId", "ParentCartellaId", "Nome") WHERE "ParentCartellaId" IS NOT NULL;

CREATE UNIQUE INDEX "UX_CategorieDpi_Nome" ON "CategorieDpi" ("Nome");

CREATE UNIQUE INDEX "UX_CategorieMateriale_Nome" ON "CategorieMateriale" ("Nome");

CREATE INDEX "IX_Dipendenti_Cognome_Nome" ON "Dipendenti" ("Cognome", "Nome");

CREATE INDEX "IX_Dipendenti_MansioneId" ON "Dipendenti" ("MansioneId");

CREATE UNIQUE INDEX "UX_Dipendenti_CodiceFiscale" ON "Dipendenti" ("CodiceFiscale") WHERE ("CodiceFiscale" IS NOT NULL);

CREATE UNIQUE INDEX "UX_Dipendenti_Matricola" ON "Dipendenti" ("Matricola") WHERE ("Matricola" IS NOT NULL);

CREATE INDEX "IX_DocumentiCantieri_CantiereId" ON "DocumentiCantieri" ("CantiereId");

CREATE INDEX "IX_DocumentiDipendenti_CartellaId" ON "DocumentiDipendenti" ("CartellaId");

CREATE INDEX "IX_DocumentiDipendenti_DataScadenza" ON "DocumentiDipendenti" ("DataScadenza");

CREATE INDEX "IX_DocumentiDipendenti_DipendenteId" ON "DocumentiDipendenti" ("DipendenteId");

CREATE INDEX "IX_DocumentiDipendenti_TipoDocumentoId" ON "DocumentiDipendenti" ("TipoDocumentoId");

CREATE INDEX "IX_DocumentiDipendenti_UploadedByUtenteId" ON "DocumentiDipendenti" ("UploadedByUtenteId");

CREATE INDEX "IX_DocumentiMezzi_DataScadenza" ON "DocumentiMezzi" ("DataScadenza");

CREATE INDEX "IX_DocumentiMezzi_MezzoId" ON "DocumentiMezzi" ("MezzoId");

CREATE INDEX "IX_DocumentiMezzi_TipoDocumentoId" ON "DocumentiMezzi" ("TipoDocumentoId");

CREATE INDEX "IX_Dpi_CategoriaDpiId" ON "Dpi" ("CategoriaDpiId");

CREATE INDEX "IX_Dpi_FornitoreId" ON "Dpi" ("FornitoreId");

CREATE INDEX "IX_Dpi_Nome" ON "Dpi" ("Nome");

CREATE UNIQUE INDEX "UX_Dpi_Barcode" ON "Dpi" ("Barcode") WHERE ("Barcode" IS NOT NULL);

CREATE UNIQUE INDEX "UX_Dpi_Codice" ON "Dpi" ("Codice") WHERE ("Codice" IS NOT NULL);

CREATE UNIQUE INDEX "UX_EsitiVisitaMedica_Nome" ON "EsitiVisitaMedica" ("Nome");

CREATE INDEX "IX_ExpenseRequests_CreatedAt" ON "ExpenseRequests" ("CreatedAt");

CREATE INDEX "IX_ExpenseRequests_DipendenteId" ON "ExpenseRequests" ("DipendenteId");

CREATE INDEX "IX_ExpenseRequests_GestitoDaUtenteId" ON "ExpenseRequests" ("GestitoDaUtenteId");

CREATE INDEX "IX_ExpenseRequests_Stato" ON "ExpenseRequests" ("Stato");

CREATE UNIQUE INDEX "UX_Fornitori_PartitaIva" ON "Fornitori" ("PartitaIva") WHERE ("PartitaIva" IS NOT NULL);

CREATE INDEX "IX_IssueReports_CreatedAt" ON "IssueReports" ("CreatedAt");

CREATE INDEX "IX_IssueReports_DipendenteId" ON "IssueReports" ("DipendenteId");

CREATE INDEX "IX_IssueReports_GestitoDaUtenteId" ON "IssueReports" ("GestitoDaUtenteId");

CREATE INDEX "IX_IssueReports_Stato" ON "IssueReports" ("Stato");

CREATE UNIQUE INDEX "UX_Mansioni_Nome" ON "Mansioni" ("Nome");

CREATE INDEX "IX_Materiali_CategoriaMaterialeId" ON "Materiali" ("CategoriaMaterialeId");

CREATE INDEX "IX_Materiali_FornitoreId" ON "Materiali" ("FornitoreId");

CREATE INDEX "IX_Materiali_Nome" ON "Materiali" ("Nome");

CREATE UNIQUE INDEX "UX_Materiali_Barcode" ON "Materiali" ("Barcode") WHERE ("Barcode" IS NOT NULL);

CREATE UNIQUE INDEX "UX_Materiali_Codice" ON "Materiali" ("Codice") WHERE ("Codice" IS NOT NULL);

CREATE INDEX "IX_MaterialRequests_CreatedAt" ON "MaterialRequests" ("CreatedAt");

CREATE INDEX "IX_MaterialRequests_DipendenteId" ON "MaterialRequests" ("DipendenteId");

CREATE INDEX "IX_MaterialRequests_GestitoDaUtenteId" ON "MaterialRequests" ("GestitoDaUtenteId");

CREATE INDEX "IX_MaterialRequests_Stato" ON "MaterialRequests" ("Stato");

CREATE INDEX "IX_Mezzi_DataRevisione" ON "Mezzi" ("DataRevisione");

CREATE INDEX "IX_Mezzi_DataScadenzaAssicurazione" ON "Mezzi" ("DataScadenzaAssicurazione");

CREATE INDEX "IX_Mezzi_FornitoreId" ON "Mezzi" ("FornitoreId");

CREATE INDEX "IX_Mezzi_TipologiaMezzoId" ON "Mezzi" ("TipologiaMezzoId");

CREATE UNIQUE INDEX "UX_Mezzi_CodiceInterno" ON "Mezzi" ("CodiceInterno") WHERE ("CodiceInterno" IS NOT NULL);

CREATE UNIQUE INDEX "UX_Mezzi_NumeroTelaio" ON "Mezzi" ("NumeroTelaio") WHERE ("NumeroTelaio" IS NOT NULL);

CREATE UNIQUE INDEX "UX_Mezzi_Targa" ON "Mezzi" ("Targa") WHERE ("Targa" IS NOT NULL);

CREATE INDEX "IX_MovimentiMateriale_CantiereId" ON "MovimentiMateriale" ("CantiereId");

CREATE INDEX "IX_MovimentiMateriale_DataMovimento" ON "MovimentiMateriale" ("DataMovimento");

CREATE INDEX "IX_MovimentiMateriale_DipendenteId" ON "MovimentiMateriale" ("DipendenteId");

CREATE INDEX "IX_MovimentiMateriale_MaterialeId" ON "MovimentiMateriale" ("MaterialeId");

CREATE INDEX "IX_MovimentiMateriale_TipoMovimentoMaterialeId" ON "MovimentiMateriale" ("TipoMovimentoMaterialeId");

CREATE UNIQUE INDEX "UX_Permessi_Codice" ON "Permessi" ("Codice");

CREATE INDEX "IX_RefreshTokens_UtenteId_ExpiresAt" ON "RefreshTokens" ("UtenteId", "ExpiresAt");

CREATE UNIQUE INDEX "UX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");

CREATE UNIQUE INDEX "UX_Ruoli_Nome" ON "Ruoli" ("Nome");

CREATE INDEX "IX_RuoliPermessi_PermessoId" ON "RuoliPermessi" ("PermessoId");

CREATE UNIQUE INDEX "UX_StatiAssegnazione_Nome" ON "StatiAssegnazione" ("Nome");

CREATE UNIQUE INDEX "UX_TipiDocumento_Nome" ON "TipiDocumento" ("Nome");

CREATE UNIQUE INDEX "UX_TipiMovimentoMateriale_Nome" ON "TipiMovimentoMateriale" ("Nome");

CREATE UNIQUE INDEX "UX_TipiVisitaMedica_Nome" ON "TipiVisitaMedica" ("Nome");

CREATE UNIQUE INDEX "UX_TipologieMezzo_Nome" ON "TipologieMezzo" ("Nome");

CREATE UNIQUE INDEX "UX_Utenti_DipendenteId" ON "Utenti" ("DipendenteId") WHERE ("DipendenteId" IS NOT NULL);

CREATE UNIQUE INDEX "UX_Utenti_Email" ON "Utenti" ("Email");

CREATE UNIQUE INDEX "UX_Utenti_Username" ON "Utenti" ("Username");

CREATE INDEX "IX_UtentiRuoli_RuoloId" ON "UtentiRuoli" ("RuoloId");

CREATE UNIQUE INDEX "UX_UtentiRuoli_UtenteId_RuoloId" ON "UtentiRuoli" ("UtenteId", "RuoloId");

CREATE UNIQUE INDEX "UX_UtentiVisibilita_UtenteId_Chiave" ON "UtentiVisibilita" ("UtenteId", "Chiave");

CREATE INDEX "IX_VisiteMediche_DataScadenza" ON "VisiteMediche" ("DataScadenza");

CREATE INDEX "IX_VisiteMediche_DipendenteId" ON "VisiteMediche" ("DipendenteId");

CREATE INDEX "IX_VisiteMediche_EsitoVisitaMedicaId" ON "VisiteMediche" ("EsitoVisitaMedicaId");

CREATE INDEX "IX_VisiteMediche_TipoVisitaMedicaId" ON "VisiteMediche" ("TipoVisitaMedicaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511093825_InitialPostgresSchema', '10.0.5');

COMMIT;

